"""
Aquires user-defined path information generated by t_rrt_time_varied.py
and plots the encoded path and time-varying cost field in order to visualize the
path along with the varying cost field.
"""

from t_rrt_time_varied import *
from json_converter import *

''' Specify which path file to read from here'''
path_file = "./out/path_information.txt"


def main():
    # 'saved_paths/' +
    json_data = JsonData(path_file)
    json_data.get_carla_agent_info(0.1)
    _, _, _, _, _, path = json_data.get_path_information()

    print([speed for (x, y, t, psi, throttle, speed) in path])

    ''' Plot the path overlayed on the time-varying cost field'''
    while True:
        for t_idx in range(0, len(json_data.data['t']) - 1):
            plt.figure(2)
            plt.clf()
            plt.ion()
            plt.contourf(json_data.mesh_grid[0], json_data.mesh_grid[1], json_data.cost_map[t_idx], 20, cmap='inferno')
            plt.plot([x for (x, y, t, psi, throttle, speed) in path[:t_idx]],
                     [y for (x, y, t, psi, throttle, speed) in path[:t_idx]], '-r')
            plt.grid(True)
            plt.xlabel('x (meters)')
            plt.ylabel('y (meters)')
            # plt.title(path_file)
            plt.show()
            plt.pause(0.1)


if __name__ == '__main__':
    main()
